# Generated by Django 5.0.4 on 2024-04-10 23:33

import django.db.models.deletion
import django.utils.timezone
import projetores.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aluguel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=150, verbose_name='dados do dia')),
                ('date', models.DateField(blank=True, null=True, validators=[projetores.models.validate_future_date], verbose_name='Data')),
            ],
            options={
                'verbose_name': 'Aluguel',
                'verbose_name_plural': 'Aluguel',
            },
        ),
        migrations.CreateModel(
            name='professor',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('matery', models.CharField(max_length=150, verbose_name='Matéria')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professor',
            },
        ),
        migrations.CreateModel(
            name='quantidadeprofessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=150, verbose_name='sala')),
                ('matery', models.CharField(max_length=150, verbose_name='matéria')),
                ('insert_in', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Inserido em')),
                ('data_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetores.aluguel', verbose_name='aluguel')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetores.professor', verbose_name='professor')),
            ],
            options={
                'verbose_name': 'lista profesor',
                'verbose_name_plural': 'lista professores',
            },
        ),
    ]
