# Generated by Django 5.0.4 on 2024-04-10 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professor',
            options={'verbose_name': 'Professor', 'verbose_name_plural': 'Professores'},
        ),
    ]
